package entite.dao;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

import com.util.HibernateUtil;

import entite.base.BaseForfaitDAO;
import entite.Forfait;
import entite.base.BaseForfait;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the forfait table.
 * Any customizations belong here.
 */
public class ForfaitDAO extends BaseForfaitDAO {
	
	private SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
	
	public List<Forfait> findAll(){
		
			
			try {
				if(!this.sessionFactory.getCurrentSession().getTransaction().isActive()){
					Transaction transaction = this.sessionFactory.getCurrentSession().getTransaction();
					Transaction tx =this.sessionFactory.getCurrentSession().beginTransaction();
					}
					Criteria crit = this.sessionFactory.getCurrentSession().createCriteria(BaseForfait.class);
//					this.sessionFactory.getCurrentSession().close();
					return crit.list();
					
		
			}catch (Exception e){
				try {
					throw e;
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
					return null;
				}
//				return null;
			}
				
		
		}

	public Forfait findByID(int idForfait){
		
		try {
			if(!this.sessionFactory.getCurrentSession().getTransaction().isActive()){
				Transaction transaction = this.sessionFactory.getCurrentSession().getTransaction();
				Transaction tx =this.sessionFactory.getCurrentSession().beginTransaction();}
			
				Forfait localite = (Forfait) this.sessionFactory.getCurrentSession().createCriteria(BaseForfait.class).add(Restrictions.eq(Forfait.PROP_ID, idForfait)).uniqueResult();
//						this.sessionFactory.getCurrentSession().close();
				return  localite;
		}catch (Exception e){
			System.out.println(e);
			return null;
		}
	
}}