package entite.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the localite table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="localite"
 */
public abstract class BaseLocalite  implements Serializable {

	public static String PROP_ADRESSE_POSTALE = "AdressePostale";
	public static String PROP_RESPONSABLE = "Responsable";
	public static String PROP_ADRESSE_I_P = "AdresseIP";
	public static String PROP_ID = "Id";
	public static String PROP_CODE = "Code";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _code;
	private java.lang.String _responsable;
	private java.lang.String _adresseIP;
	private java.lang.String _adressePostale;

	// collections
	private java.util.Set _ligneSet;


	// constructors
	public BaseLocalite () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseLocalite (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseLocalite (
		java.lang.Integer _id,
		java.lang.String _code) {

		this.setId(_id);
		this.setCode(_code);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: code
	 */
	public java.lang.String getCode () {
		return _code;
	}

	/**
	 * Set the value related to the column: code
	 * @param _code the code value
	 */
	public void setCode (java.lang.String _code) {
		this._code = _code;
	}


	/**
	 * Return the value associated with the column: responsable
	 */
	public java.lang.String getResponsable () {
		return _responsable;
	}

	/**
	 * Set the value related to the column: responsable
	 * @param _responsable the responsable value
	 */
	public void setResponsable (java.lang.String _responsable) {
		this._responsable = _responsable;
	}


	/**
	 * Return the value associated with the column: adresseIP
	 */
	public java.lang.String getAdresseIP () {
		return _adresseIP;
	}

	/**
	 * Set the value related to the column: adresseIP
	 * @param _adresseIP the adresseIP value
	 */
	public void setAdresseIP (java.lang.String _adresseIP) {
		this._adresseIP = _adresseIP;
	}


	/**
	 * Return the value associated with the column: adressePostale
	 */
	public java.lang.String getAdressePostale () {
		return _adressePostale;
	}

	/**
	 * Set the value related to the column: adressePostale
	 * @param _adressePostale the adressePostale value
	 */
	public void setAdressePostale (java.lang.String _adressePostale) {
		this._adressePostale = _adressePostale;
	}


	/**
	 * Return the value associated with the column: LigneSet
	 */
	public java.util.Set getLigneSet () {
		return this._ligneSet;
	}

	/**
	 * Set the value related to the column: LigneSet
	 * @param _ligneSet the LigneSet value
	 */
	public void setLigneSet (java.util.Set _ligneSet) {
		this._ligneSet = _ligneSet;
	}
	
	public void addToLigneSet (Object obj) {
		if (null == this._ligneSet) this._ligneSet = new java.util.HashSet();
		this._ligneSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof entite.base.BaseLocalite)) return false;
		else {
			entite.base.BaseLocalite mObj = (entite.base.BaseLocalite) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}