package entity.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the LiaisonTypeForfait table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="LiaisonTypeForfait"
 */
public abstract class BaseLiaisonTypeForfait  implements Serializable {

	public static String PROP_TYPE = "Type";
	public static String PROP_FORFAIT = "Forfait";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// many to one
	private entity.Type _type;
	private entity.Forfait _forfait;


	// constructors
	public BaseLiaisonTypeForfait () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseLiaisonTypeForfait (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseLiaisonTypeForfait (
		java.lang.Integer _id,
		entity.Type _type,
		entity.Forfait _forfait) {

		this.setId(_id);
		this.setType(_type);
		this.setForfait(_forfait);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
     * @hibernate.property
     *  column=type
	 * not-null=true
	 */
	public entity.Type getType () {
		return this._type;
	}

	/**
	 * Set the value related to the column: type
	 * @param _type the type value
	 */
	public void setType (entity.Type _type) {
		this._type = _type;
	}


	/**
     * @hibernate.property
     *  column=forfait
	 * not-null=true
	 */
	public entity.Forfait getForfait () {
		return this._forfait;
	}

	/**
	 * Set the value related to the column: forfait
	 * @param _forfait the forfait value
	 */
	public void setForfait (entity.Forfait _forfait) {
		this._forfait = _forfait;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof entity.base.BaseLiaisonTypeForfait)) return false;
		else {
			entity.base.BaseLiaisonTypeForfait mObj = (entity.base.BaseLiaisonTypeForfait) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}