package entity.dao;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

import com.util.HibernateUtil;

import entity.Forfait;
import entity.LiaisonTypeForfait;
import entity.Type;
import entity.base.BaseLiaisonTypeForfait;
import entity.base.BaseLiaisonTypeForfaitDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the LiaisonTypeForfait table.
 * Any customizations belong here.
 */
public class LiaisonTypeForfaitDAO extends BaseLiaisonTypeForfaitDAO {
	
private SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
	
	public List<LiaisonTypeForfait> findAll(){
		
			
			try {
				if(!this.sessionFactory.getCurrentSession().getTransaction().isActive()){
					Transaction transaction = this.sessionFactory.getCurrentSession().getTransaction();
					Transaction tx =this.sessionFactory.getCurrentSession().beginTransaction();
					}
					Criteria crit = this.sessionFactory.getCurrentSession().createCriteria(BaseLiaisonTypeForfait.class);
					return crit.list();
					
		
			}catch (Exception e){
				try {
					throw e;
				} catch (Exception e1) {
					e1.printStackTrace();
					return null;
				}
			}
				
		
		}
	
	
	public List<LiaisonTypeForfait> findByType(Type type){
		
		try {
			if(!this.sessionFactory.getCurrentSession().getTransaction().isActive()){
				Transaction transaction = this.sessionFactory.getCurrentSession().getTransaction();
				Transaction tx =this.sessionFactory.getCurrentSession().beginTransaction();}
			
				List<LiaisonTypeForfait> ligne = (List<LiaisonTypeForfait>) this.sessionFactory.getCurrentSession().createCriteria(BaseLiaisonTypeForfait.class).add(Restrictions.eq(LiaisonTypeForfait.PROP_TYPE, type)).list();
//						this.sessionFactory.getCurrentSession().close();
				return  ligne;
		}catch (Exception e){
			System.out.println(e);
			return null;
		}
			

	}
	
	
	public void insertLiaisonTypeForfait(LiaisonTypeForfait localite,boolean uniqueInsert){
		try {
			
//			sessionFactory = HibernateUtil.getSessionFactory();
			
//			localite.setId(-1);
			if(!this.sessionFactory.getCurrentSession().getTransaction().isActive()){
				this.sessionFactory.getCurrentSession().getTransaction().begin();}
			this.sessionFactory.getCurrentSession().save((BaseLiaisonTypeForfait) localite);
			if(uniqueInsert)
			this.sessionFactory.getCurrentSession().getTransaction().commit();
//			this.sessionFactory.getCurrentSession().persist(localite);
//			this.sessionFactory.getCurrentSession().flush();
//			this.sessionFactory.getCurrentSession().close();
		}catch (Exception e){
			this.sessionFactory.getCurrentSession().getTransaction().rollback();
//			throw e;
		}
	}


	public List<LiaisonTypeForfait> findByForfait(Forfait forfait) {
		try {
			if(!this.sessionFactory.getCurrentSession().getTransaction().isActive()){
				Transaction transaction = this.sessionFactory.getCurrentSession().getTransaction();
				Transaction tx =this.sessionFactory.getCurrentSession().beginTransaction();}
			
				List<LiaisonTypeForfait> ligne = (List<LiaisonTypeForfait>) this.sessionFactory.getCurrentSession().createCriteria(BaseLiaisonTypeForfait.class).add(Restrictions.eq(LiaisonTypeForfait.PROP_FORFAIT, forfait)).list();
//						this.sessionFactory.getCurrentSession().close();
				return  ligne;
		}catch (Exception e){
			System.out.println(e);
			return null;
		}
	}


	public void deleteListe(List<LiaisonTypeForfait> listeLiaisonTypeForfait) throws Exception {
		// TODO Auto-generated method stub
		for(int i = 0; i < listeLiaisonTypeForfait.size(); i++){
	    	this.deleteLigne(listeLiaisonTypeForfait.get(i),false);
	  }
	    this.sessionFactory.getCurrentSession().getTransaction().commit();
	}
	
	
	
	public void deleteLigne(LiaisonTypeForfait liaisonTypeForfait,boolean uniqueInsert) throws Exception{
		try {
			
			if(!this.sessionFactory.getCurrentSession().getTransaction().isActive()){
				this.sessionFactory.getCurrentSession().getTransaction().begin();}
			this.sessionFactory.getCurrentSession().delete((BaseLiaisonTypeForfait) liaisonTypeForfait);
			if(uniqueInsert)
			this.sessionFactory.getCurrentSession().getTransaction().commit();
		}catch (Exception e){
			this.sessionFactory.getCurrentSession().getTransaction().rollback();
			throw e;
		}
	}
	
	
}