package entity.dao;

import entity.base.BaseLigneDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the ligne table.
 * Any customizations belong here.
 */
public class LigneDAO extends BaseLigneDAO {
}