package entity.dao;

import entity.Type;
import entity.Type;
import entity.base.BaseType;
import entity.base.BaseType;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

import com.util.HibernateUtil;

import entity.base.BaseTypeDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the type table.
 * Any customizations belong here.
 */
public class TypeDAO extends BaseTypeDAO {
	
	private SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
	
public List<Type> findAll(){
	
		
		try {
			if(!this.sessionFactory.getCurrentSession().getTransaction().isActive()){
				Transaction transaction = this.sessionFactory.getCurrentSession().getTransaction();
				Transaction tx =this.sessionFactory.getCurrentSession().beginTransaction();
				}
				Criteria crit = this.sessionFactory.getCurrentSession().createCriteria(BaseType.class);
//				this.sessionFactory.getCurrentSession().close();
				return crit.list();
				
	
		}catch (Exception e){
			try {
				throw e;
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
				return null;
			}
//			return null;
		}
			
	
	}

public Type findByID(String numeroType){
	
	try {
		if(!this.sessionFactory.getCurrentSession().getTransaction().isActive()){
			Transaction transaction = this.sessionFactory.getCurrentSession().getTransaction();
			Transaction tx =this.sessionFactory.getCurrentSession().beginTransaction();}
		
			Type localite = (Type) this.sessionFactory.getCurrentSession().createCriteria(BaseType.class).add(Restrictions.eq(Type.PROP_ID, numeroType)).uniqueResult();
//					this.sessionFactory.getCurrentSession().close();
			return  localite;
	}catch (Exception e){
		System.out.println(e);
		return null;
	}
		

}

}