package hibernateEntity.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the porteur table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="porteur"
 */
public abstract class BasePorteur  implements Serializable {

	public static String PROP_LIGNE = "Ligne";
	public static String PROP_ID = "Id";
	public static String PROP_NOM = "Nom";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _nom;

	// many to one
	private hibernateEntity.Ligne _ligne;


	// constructors
	public BasePorteur () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePorteur (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BasePorteur (
		java.lang.Integer _id,
		hibernateEntity.Ligne _ligne,
		java.lang.String _nom) {

		this.setId(_id);
		this.setLigne(_ligne);
		this.setNom(_nom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
     * @hibernate.property
     *  column=ligne
	 * not-null=true
	 */
	public hibernateEntity.Ligne getLigne () {
		return this._ligne;
	}

	/**
	 * Set the value related to the column: ligne
	 * @param _ligne the ligne value
	 */
	public void setLigne (hibernateEntity.Ligne _ligne) {
		this._ligne = _ligne;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernateEntity.base.BasePorteur)) return false;
		else {
			hibernateEntity.base.BasePorteur mObj = (hibernateEntity.base.BasePorteur) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}