package hibernateEntity.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the facture table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="facture"
 */
public abstract class BaseFacture  implements Serializable {

	public static String PROP_FRAIS = "Frais";
	public static String PROP_LIGNE = "Ligne";
	public static String PROP_ANNEE = "Annee";
	public static String PROP_MOIS = "Mois";
	public static String PROP_ID = "Id";
	public static String PROP_ID_FACTURE = "IdFacture";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _idFacture;
	private java.lang.String _annee;
	private java.lang.Float _frais;
	private java.lang.String _mois;

	// many to one
	private hibernateEntity.Ligne _ligne;


	// constructors
	public BaseFacture () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseFacture (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseFacture (
		java.lang.Integer _id,
		hibernateEntity.Ligne _ligne,
		java.lang.String _idFacture,
		java.lang.String _annee,
		java.lang.Float _frais,
		java.lang.String _mois) {

		this.setId(_id);
		this.setLigne(_ligne);
		this.setIdFacture(_idFacture);
		this.setAnnee(_annee);
		this.setFrais(_frais);
		this.setMois(_mois);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: ID_facture
	 */
	public java.lang.String getIdFacture () {
		return _idFacture;
	}

	/**
	 * Set the value related to the column: ID_facture
	 * @param _idFacture the ID_facture value
	 */
	public void setIdFacture (java.lang.String _idFacture) {
		this._idFacture = _idFacture;
	}


	/**
	 * Return the value associated with the column: annee
	 */
	public java.lang.String getAnnee () {
		return _annee;
	}

	/**
	 * Set the value related to the column: annee
	 * @param _annee the annee value
	 */
	public void setAnnee (java.lang.String _annee) {
		this._annee = _annee;
	}


	/**
	 * Return the value associated with the column: frais
	 */
	public java.lang.Float getFrais () {
		return _frais;
	}

	/**
	 * Set the value related to the column: frais
	 * @param _frais the frais value
	 */
	public void setFrais (java.lang.Float _frais) {
		this._frais = _frais;
	}


	/**
	 * Return the value associated with the column: mois
	 */
	public java.lang.String getMois () {
		return _mois;
	}

	/**
	 * Set the value related to the column: mois
	 * @param _mois the mois value
	 */
	public void setMois (java.lang.String _mois) {
		this._mois = _mois;
	}


	/**
     * @hibernate.property
     *  column=ligne
	 * not-null=true
	 */
	public hibernateEntity.Ligne getLigne () {
		return this._ligne;
	}

	/**
	 * Set the value related to the column: ligne
	 * @param _ligne the ligne value
	 */
	public void setLigne (hibernateEntity.Ligne _ligne) {
		this._ligne = _ligne;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernateEntity.base.BaseFacture)) return false;
		else {
			hibernateEntity.base.BaseFacture mObj = (hibernateEntity.base.BaseFacture) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}